### ISSUE TITLE
gpg: command not found

### ISSUE THREAD

**Issue by sureshgoli25** [EngineerBetter/pcfops-docker#1]
https://github.com/EngineerBetter/pcfops-docker/blob/b8d64019c9e016c4eb018b48c2904954e87ae682/Dockerfile#L19

Hi, We are using pcf-ops image (	sha256:160b2bed5143f4dd67afc41585d8493f4f61a94b483077e4b529c532e08705d4) for encryption/decryption of  sensitive information in our concourse PCF CI/CD pipelines.
We are seeing the **GPG command not found** exception since 19-01-2019 while running our pipelines.

is it possible to add GPG binary as well into pcf-ops image while composing docker image which can be useful for us and everyone who like to use gpg encryption/decryption on fly.

**Comment by crsimmons** [comment]
Hey Suresh. Sorry about that. On Friday we bumped the base image from cflinuxfs2 (trusty) to cflinuxfs3 (bionic) since the former will be out of support soon. I guess gpg was removed from the base os. I'll look at adding this today. In the mean time you can pin to the previous version.

**Comment by sureshgoli25** [comment]
Hi Colin, Yes. For now we have pin down version and also we download the GPG on fly **apt-get install gnupg2 -y >/dev/null 2>&1**  just in case if it is not presented in previous release. And now our pipelines are green again.

**Comment by dark5un** [comment]
GPG is now present in v1.1.0+ on dockerhub. Let us know how it goes.

**Comment by sureshgoli25** [comment]
Thank you. I have pulled new image and it worked for me.
